import { cn } from '@/utils/cn';
import './globals.css';
import React from 'react';
import type { Metadata } from 'next';
import { TooltipProvider } from '@radix-ui/react-tooltip';
import { ThemeProvider } from 'next-themes';

import { Providers } from '@/app/providers';
import GoogleMapsProvider from '@/components/GoogleMapsProvider';

export const metadata: Metadata = {
  title: 'RAFF',
  description: 'Generated by create next app',
  // robots: {
  //   index: false,
  //   follow: false,
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      className={cn('font-sans bg-bg-white-0 antialiased')}
    >
      <body className='bg-bg-white-0'>
        <GoogleMapsProvider>
        <Providers>
          <ThemeProvider attribute='class'>
            <TooltipProvider
              delayDuration={100}
              skipDelayDuration={300}
              disableHoverableContent
            >
              {children}
            </TooltipProvider>
          </ThemeProvider>
        </Providers>
        </GoogleMapsProvider>
      </body>
    </html>
  );
}
